<?php 
/*
 * 
	This file contains anything that needs to be included prior to loading control.inc; prerequisites (includes), custom PageClass, custom class definitions, etc.	
 *
*/

/* class indexPage extends proteusPage
{
	public $pageIndex = "index";
	
	// Default to standard
	public function __construct($title="")
	{		
		// Can set a custom view file in here for all pages if necessary
		// When setting a custom view (.tpl), the parser is set to "absolute" file path
		// $template = "pages/index/file.tpl;
		
		// To use the standard custom view template (/pages/pageIndex/view.tpl), use the built-in shortcut option from pageClass:
		// $this->setCustomView()
		
		parent::__construct($title);
	}	
} */
?>